---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024-2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  # Enable memory protection and usage throttle on pod / container using cgroup v2 memory controller.
  "MemoryQoS": true
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
kubeadmConfigPatches:
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    serializeImagePulls: false
nodes:
  - role: control-plane
    image: kindest/node:v1.31.1
  - role: worker
    image: kindest/node:v1.31.1
  - role: worker
    image: kindest/node:v1.31.1
  - role: worker
    image: kindest/node:v1.31.1
  - role: worker
    image: kindest/node:v1.31.1
  - role: worker
    image: kindest/node:v1.31.1
  - role: worker
    image: kindest/node:v1.31.1
