---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
services:
  registry:
    image: registry:2
    volumes:
      - images:/var/lib/registry
  web-server:
    build:
      context: ./nginx
    links:
      - registry:docker-registry
    image: electrocucaracha/nginx:vts
    ports:
      - 5001:5001/tcp
volumes:
  images:
    driver: local
    driver_opts:
      type: bind
      device: /var/local/images
      o: bind
