---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Check End-to-End (On Demand)
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.sh"
      - "!.github/*"
  pull_request_review:
    types:
      - submitted
jobs:
  check-scripts-format:
    if: >-
      ( github.event_name == 'pull_request_review' && github.event.review.state == 'approved' ) || github.event_name != 'pull_request_review'
    name: Check scripts format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@17bd25a6ee188d2b91f677060038f4ba37ba14b2 # 0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -i 4 -s
        with:
          sh_checker_shellcheck_disable: true
  smoke-test:
    name: Check smoke tests
    needs: check-scripts-format
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - enable_stargz_snapshotter: true
          - enable_stargz_snapshotter: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Setup environment
        working-directory: ./scripts
        env:
          DEBUG: true
          ENABLE_STARGZ_SNAPSHOTTER: ${{ matrix.enable_stargz_snapshotter }}
        run: ./main.sh
      - name: Run Distroless demo
        run: ./demo.sh
